name: CI
on: [pull_request]

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      env:
        REF: ${{ github. sha }}
      run: docker build -t gathering-demeter:${REF##*/} .

